### ISSUE TITLE
Better ESP with nice skeleton if you want to add just copy paste to esp.hpp :)

### ISSUE THREAD

**Issue by SteveKiller** [fir3z/External-R6-Cheat#3]
vec3_t ass = get_bone_pos_by_id(entity.pawn, 20);
		vec3_t shoulderR = get_bone_pos_by_id(entity.pawn, 7);
		vec3_t shoulderL = get_bone_pos_by_id(entity.pawn, 10);
		vec3_t armL = get_bone_pos_by_id(entity.pawn, 19);
		vec3_t armR = get_bone_pos_by_id(entity.pawn, 8);
		vec3_t handL = get_bone_pos_by_id(entity.pawn, 18);
		vec3_t handR = get_bone_pos_by_id(entity.pawn, 9);
		vec3_t legL = get_bone_pos_by_id(entity.pawn, 21);
		vec3_t legR = get_bone_pos_by_id(entity.pawn, 25);
		vec3_t footL = get_bone_pos_by_id(entity.pawn, 22);
		vec3_t footR = get_bone_pos_by_id(entity.pawn, 26);

		vec3_t foot = get_bone_pos_by_id(entity.pawn, 0);

		vec3_t w2s_head{};
		if (!globals::camera_manager->world_to_screen(head, w2s_head)) continue;

		vec3_t w2s_ass{};
		if (!globals::camera_manager->world_to_screen(ass, w2s_ass)) continue;
		vec3_t w2s_shoulderR{};
		if (!globals::camera_manager->world_to_screen(shoulderR, w2s_shoulderR)) continue;
		vec3_t w2s_shoulderL{};
		if (!globals::camera_manager->world_to_screen(shoulderL, w2s_shoulderL)) continue;
		vec3_t w2s_armR{};
		if (!globals::camera_manager->world_to_screen(armR, w2s_armR)) continue;
		vec3_t w2s_armL{};
		if (!globals::camera_manager->world_to_screen(armL, w2s_armL)) continue;
		vec3_t w2s_handR{};
		if (!globals::camera_manager->world_to_screen(handR, w2s_handR)) continue;
		vec3_t w2s_handL{};
		if (!globals::camera_manager->world_to_screen(handL, w2s_handL)) continue;
		vec3_t w2s_legL{};
		if (!globals::camera_manager->world_to_screen(legL, w2s_legL)) continue;
		vec3_t w2s_legR{};
		if (!globals::camera_manager->world_to_screen(legR, w2s_legR)) continue;
		vec3_t w2s_footL{};
		if (!globals::camera_manager->world_to_screen(footL, w2s_footL)) continue;
		vec3_t w2s_footR{};
		if (!globals::camera_manager->world_to_screen(footR, w2s_footR)) continue;
		vec3_t w2s_foot{};
		if (!globals::camera_manager->world_to_screen(foot, w2s_foot)) continue;

		
		ImGui::GetWindowDrawList()->AddLine({ w2s_head.x, w2s_head.y }, { w2s_shoulderR.x , w2s_shoulderR.y}, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_head.x, w2s_head.y }, { w2s_shoulderL.x , w2s_shoulderL.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_shoulderL.x, w2s_shoulderL.y }, { w2s_armL.x , w2s_armL.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_armL.x, w2s_armL.y }, { w2s_handL.x , w2s_handL.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_shoulderR.x, w2s_shoulderR.y }, { w2s_armR.x , w2s_armR.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_armR.x, w2s_armR.y }, { w2s_handR.x , w2s_handR.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_head.x, w2s_head.y }, { w2s_ass.x , w2s_ass.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_ass.x, w2s_ass.y }, { w2s_legL.x , w2s_legL.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_legL.x, w2s_legL.y }, { w2s_footL.x , w2s_footL.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_ass.x, w2s_ass.y }, { w2s_legR.x , w2s_legR.y }, ImColor(0.f, 0.f, 1.f));
		ImGui::GetWindowDrawList()->AddLine({ w2s_legR.x, w2s_legR.y }, { w2s_footR.x , w2s_footR.y }, ImColor(0.f, 0.f, 1.f));

**Comment by fir3z** [comment]
I'll add in a lil bit.
